data {
  int<lower=1> N_C;
  int<lower=3> TT;
  vector<lower=0>[N_C] pop_size;
  array[TT - 1, N_C] int<lower=0> ii;
  array[N_C] int<lower=2, upper=TT - 1> first;
  int<lower=1> N_wks_per_period;
}

transformed data {
  array[N_C] int n_beta_per_county;
  int n_beta;
  int glob_beta_start = min(first);
  int n_glob_beta = TT - glob_beta_start + 1;
  array[N_C] int idx_starts;
  array[N_C] int idx_ends;
  array[TT - 1] int p_idx;

  for (c in 1:N_C) {
    n_beta_per_county[c] = TT - first[c];
  }
  n_beta = sum(n_beta_per_county);
  idx_starts[1] = 1;
  idx_ends[1] = n_beta_per_county[1];
  if (N_C > 1) {
    for (c in 2:N_C) {
      idx_starts[c] = idx_ends[c - 1] + 1;
      idx_ends[c] = idx_starts[c] + n_beta_per_county[c] - 1;
    }
  }
  for (t in 1:(TT - 1)) {
    p_idx[t] = (t - 1) %/% N_wks_per_period + 1;
  }
  int n_p_pers = max(p_idx);
}

parameters {
  matrix[TT, N_C] u_t_logit_eta;
  matrix[TT, N_C] w_t_logit_eta;
  matrix[TT, N_C] v_t_logit_eta;
  vector[n_beta] raw_log_beta;

  real mu_log_beta;
  vector[n_glob_beta] z;
  real<lower=0> sigma;
  vector<lower=0>[N_C] sig_beta;
  vector[n_p_pers] eta_p_time;
  real log_obs_cv;

  // Expected reported count from the boundary E -> I flow. Parameterizing
  // this observed-scale quantity separates the initial scale from p.
  vector[N_C] log_initial_reported_count;

  array[N_C] real eta_raw;
  array[N_C] real gamma_raw;
  real v_raw;
  real rho_ir_raw;
  real rho_ei_raw;
}

transformed parameters {
  matrix[TT, N_C] s_t = rep_matrix(1, TT, N_C);
  matrix[TT, N_C] e_t = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] i_t = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] se_t = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] ei_t = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] ir_t = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] u_t = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] v_t = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] w_t = rep_matrix(0, TT, N_C);
  vector[TT] log_beta = rep_vector(0, TT);
  matrix[TT, N_C] log_beta_mat = rep_matrix(0, TT, N_C);
  matrix[TT, N_C] beta_mat = rep_matrix(0, TT, N_C);
  matrix[TT - 1, N_C] p;

  real v = inv_logit(v_raw);
  real phi = 2 * v - 1;
  real<lower=0> obs_cv = exp(log_obs_cv);
  // real<lower=0, upper=1> rho_ei = 0;
  // real<lower=0, upper=1> rho_ir = 0;

  real<lower=0, upper=1> rho_ei = inv_logit(rho_ei_raw);
  real<lower=0, upper=1> rho_ir = inv_logit(rho_ir_raw);
  array[N_C] real<lower=0, upper=1> gamma = inv_logit(gamma_raw);
  array[N_C] real<lower=0, upper=1> eta = inv_logit(eta_raw);

  vector<lower=0>[N_C] initial_reported_count;
  vector[N_C] log_initial_ei_count;
  vector<lower=0>[N_C] initial_ei_count;
  vector<lower=0, upper=1>[N_C] initial_ei;
  vector<lower=0, upper=1>[N_C] initial_e;
  vector<lower=0, upper=1>[N_C] initial_i;
  vector<lower=0, upper=1>[N_C] initial_s;

  for (t in 1:(TT - 1)) {
    for (ct in 1:N_C) {
      p[t, ct] = inv_logit(eta_p_time[p_idx[t]]);
    }
  }

  // Let F0 denote the first-week E -> I incidence flow. Under a locally
  // stationary boundary, E0 = F0 / eta and I0 = F0 / gamma. The parameter
  // lambda0 = p * F0_count is on the scale directly observed by the data.
  for (ct in 1:N_C) {
    initial_reported_count[ct] = exp(log_initial_reported_count[ct]);
    log_initial_ei_count[ct] = log_initial_reported_count[ct]
                               - log(p[first[ct], ct]);
    initial_ei_count[ct] = exp(log_initial_ei_count[ct]);
    initial_ei[ct] = initial_ei_count[ct] / pop_size[ct];
    initial_e[ct] = initial_ei[ct] / eta[ct];
    initial_i[ct] = initial_ei[ct] / gamma[ct];
    initial_s[ct] = 1 - initial_e[ct] - initial_i[ct];

    s_t[first[ct], ct] = initial_s[ct];
    e_t[first[ct], ct] = initial_e[ct];
    i_t[first[ct], ct] = initial_i[ct];
    ei_t[first[ct], ct] = initial_ei[ct];
  }

  // Centered, stationary AR(1) for the statewide transmission trajectory.
  log_beta[glob_beta_start] = mu_log_beta
    + sigma / sqrt(1 - square(phi)) * z[1];
  for (n in (glob_beta_start + 1):TT) {
    log_beta[n] = mu_log_beta
      + phi * (log_beta[n - 1] - mu_log_beta)
      + sigma * z[n - glob_beta_start + 1];
  }

  for (ct in 1:N_C) {
    log_beta_mat[first[ct]:(TT - 1), ct] =
      log_beta[first[ct]:(TT - 1)]
      + sig_beta[ct] * raw_log_beta[idx_starts[ct]:idx_ends[ct]];
    beta_mat[first[ct]:(TT - 1), ct] =
      exp(log_beta_mat[first[ct]:(TT - 1), ct]);
  }

  for (ct in 1:N_C) {
    for (n in (first[ct] + 1):TT) {
      int t = n - 1;
      real u_t_mean;

      u_t_mean = exponential_cdf(beta_mat[t, ct] * i_t[t, ct] | 1);
      u_t[t, ct] = inv_logit(
          u_t_logit_eta[t, ct]
          * sqrt(inv(pop_size[ct] * s_t[t, ct]
                     * u_t_mean * (1 - u_t_mean)))
          + logit(u_t_mean));

      // Keep the seeded first-week incidence; calculate later E-to-I flows
      // from the exposed compartment generated by the previous week's I state.
      if (t > first[ct]) {
        v_t[t, ct] = inv_logit(
          v_t_logit_eta[t, ct]
          * sqrt((1 - rho_ei)
                 / (pop_size[ct] * e_t[t, ct]
                    * eta[ct] * (1 - eta[ct]))
                 + rho_ei / (eta[ct] * (1 - eta[ct])))
          + logit(eta[ct]));
        ei_t[t, ct] = v_t[t, ct] * e_t[t, ct];
      }

      w_t[t, ct] = inv_logit(
          w_t_logit_eta[t, ct]
          * sqrt((1 - rho_ir)
                 / (pop_size[ct] * i_t[t, ct]
                    * gamma[ct] * (1 - gamma[ct]))
                 + rho_ir / (gamma[ct] * (1 - gamma[ct])))
          + logit(gamma[ct]));
      se_t[t, ct] = u_t[t, ct] * s_t[t, ct];
      ir_t[t, ct] = w_t[t, ct] * i_t[t, ct];

      s_t[n, ct] = s_t[t, ct] - se_t[t, ct];
      // Boundary stocks and the boundary flow are distinct, so the ordinary
      // mass-conserving update also applies in the first modeled week.
      e_t[n, ct] = e_t[t, ct] + se_t[t, ct] - ei_t[t, ct];
      i_t[n, ct] = i_t[t, ct] + ei_t[t, ct] - ir_t[t, ct];
    }
  }
}

model {
  rho_ir_raw ~ logistic(0, 1);
  rho_ei_raw ~ normal(logit(0.2), 0.75);
  v_raw ~ normal(logit(0.9), 0.3);
  mu_log_beta ~ normal(-2, 2);
  sigma ~ normal(0, .15);
  sig_beta ~ normal(0, .15);

  // Preserve the earlier broad lognormal prior on latent first-week incidence
  // while sampling its observed-scale counterpart lambda0 = p * F0_count.
  for (ct in 1:N_C) {
    log_initial_reported_count[ct] - log(p[first[ct], ct])
      ~ normal(log(20), 1.5);
  }

  gamma_raw ~ normal(logit(0.75), 0.5);
  eta_p_time ~ logistic(0, 1); // normal(logit(.15),.5); //logistic(0, 1);
  eta_raw ~ normal(logit(0.75), 1);
  log_obs_cv ~ normal(log(0.10), 0.35);

  z ~ std_normal();
  to_vector(u_t_logit_eta) ~ std_normal();
  to_vector(v_t_logit_eta) ~ std_normal();
  to_vector(w_t_logit_eta) ~ std_normal();
  raw_log_beta ~ std_normal();

  for (ct in 1:N_C) {
    for (t in first[ct]:(TT - 1)) {
      real n_ei = ei_t[t, ct] * pop_size[ct];
      real mu_y = p[t, ct] * n_ei;
      real var_binomial = n_ei * p[t, ct] * (1 - p[t, ct]);
      real var_reporting = 0; // square(obs_cv * mu_y);

      // Moment-matched binomial thinning with additional reporting noise.
      ii[t, ct] ~ normal(mu_y, sqrt(var_binomial + var_reporting));
    }
  }
}

generated quantities {
  real expected_detectable = 0;
  real observed_cases = 0;
  real average_p;

  for (ct in 1:N_C) {
    for (t in first[ct]:(TT - 1)) {
      observed_cases += ii[t, ct];
      expected_detectable += ei_t[t, ct] * pop_size[ct];
    }
  }
  average_p = observed_cases / expected_detectable;
}
